[package]
name = "atcoder-submit-cli"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]

[dependencies]
clap = "2.29"
error-chain = "0.11"
scraper = "0.4.0"
reqwest = "0.8.4"
hyper = "0.11"
cookie = "0.10"